language: swift
osx_image: xcode9.2
script:
  - xcodebuild clean test -scheme YARCH -workspace YARCH.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.2' -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'YARCH'